name: VanillaPlus
version: ${project.version}
main: com.edzdez.vanillaplus.VanillaPlus
api-version: 1.13
authors: [edzdez]
description: Adds a lot of features to your spigot/paper server, such as /heal, /fly, /craft, /spawn, /back, and autosmelting
