name: VanillaPlus
version: 1.0-SNAPSHOT
main: com.edzdez.vanillaplus.VanillaPlus
api-version: 1.13
authors: [edzdez]
description: Adds a lot of features to your spigot/paper server, such as /heal, /fly, /craft, /spawn, /back, and autosmelting

commands:
  heal:
    description: This is the heal command!
  fly:
    description: This is the fly command!